#!/usr/bin/env python3
# ABOUTME: Emits a C header with a small GEMM and its exact qlinear() result, for the SoC driver test.
# ABOUTME: The emulator stays the specification -- the CV32E40P compares against these numbers at runtime.

from __future__ import annotations

import argparse
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

from sw.kernels_float import gelu  # noqa: E402
from sw.kernels_int import (apply_unary_lut, build_exp_lut, build_unary_lut,  # noqa: E402
                            exact_int_matmul, qadd, qlayernorm, qlinear, qsoftmax)
from sw.numerics import INT8_MAX, INT8_MIN, Requant  # noqa: E402

# Emulator-side scales, mirrored by the constants the driver programs.
SM_SCALE_IN = 0.02
SM_SCALE_OUT = 1.0 / 127.0
LN_SCALE_IN = 1.0 / 64.0
LN_SCALE_GAMMA = 1.0 / 100.0
LN_SCALE_OUT = 1.0 / 127.0
LN_EPS = 1e-6

ROWS = 16
COLS = 16


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--seed", type=int, default=20260818)
    ap.add_argument("-m", type=int, default=24)
    ap.add_argument("-k", type=int, default=32)
    ap.add_argument("-n", type=int, default=32)
    ap.add_argument("--sm-rows", type=int, default=2)
    ap.add_argument("--sm-len", type=int, default=32)
    ap.add_argument("--ln-rows", type=int, default=2)
    ap.add_argument("--ln-len", type=int, default=40)
    ap.add_argument("--vec-n", type=int, default=64)
    ap.add_argument("-o", type=pathlib.Path, required=True)
    args = ap.parse_args()

    rng = np.random.default_rng(args.seed)
    m, k, n = args.m, args.k, args.n
    kt, nt = (k + ROWS - 1) // ROWS, (n + COLS - 1) // COLS
    kp, npad = kt * ROWS, nt * COLS

    x = rng.integers(INT8_MIN, INT8_MAX + 1, size=(m, k), dtype=np.int64).astype(np.int8)
    w = rng.integers(INT8_MIN, INT8_MAX + 1, size=(n, k), dtype=np.int64).astype(np.int8)
    bias = rng.integers(-(1 << 16), 1 << 16, size=n, dtype=np.int64).astype(np.int32)

    acc_max = max(int(np.abs(exact_int_matmul(x, w.T) + bias).max()), 1)
    rq = Requant.from_real_multiplier(np.exp2(rng.uniform(-1.0, 3.0, size=n)) / acc_max)
    y = qlinear(x, w, bias, rq)

    xp = np.zeros((m, kp), dtype=np.int8);    xp[:, :k] = x
    wp = np.zeros((kp, npad), dtype=np.int8); wp[:k, :n] = w.T
    biasp = np.zeros(npad, dtype=np.int64);   biasp[:n] = bias
    multp = np.full(npad, 1 << 30, dtype=np.int64)
    shiftp = np.full(npad, 30, dtype=np.int64)
    multp[:n] = np.asarray(rq.multiplier).ravel()
    shiftp[:n] = np.asarray(rq.shift).ravel()

    def u32_words(packed: np.ndarray) -> list[int]:
        """Pack int8 lanes little-endian into the 32-bit words the CPU stores."""
        # int() first: shifting a numpy uint8 left by 8 wraps to zero.
        b = packed.astype(np.uint8).reshape(-1, 4)
        return [int(b[i, 0]) | (int(b[i, 1]) << 8)
                | (int(b[i, 2]) << 16) | (int(b[i, 3]) << 24)
                for i in range(b.shape[0])]

    def carr(name: str, vals: list[int]) -> str:
        body = ",\n    ".join(", ".join(f"0x{v:08x}" for v in vals[i:i + 6])
                              for i in range(0, len(vals), 6))
        # 16-byte alignment: the weight DMA reads whole 128-bit words and drops
        # the low four source address bits, so an unaligned array would be read
        # from the wrong offset.
        return (f"static const uint32_t __attribute__((aligned(16)))\n"
                f"{name}[{len(vals)}] = {{\n    {body}\n}};\n")

    out = [
        "/* Generated by test/v2/gen_driver_vectors.py -- do not edit. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define GEMM_M {m}",
        f"#define GEMM_K {k}",
        f"#define GEMM_N {n}",
        f"#define GEMM_KT {kt}",
        f"#define GEMM_NT {nt}",
        "",
        carr("gemm_act", u32_words(xp.ravel())),
        carr("gemm_wgt", u32_words(wp.ravel())),
        carr("gemm_bias", [int(v) & 0xFFFFFFFF for v in biasp]),
        carr("gemm_mult", [int(v) & 0xFFFFFFFF for v in multp]),
        carr("gemm_shift", [int(v) for v in shiftp]),
        carr("gemm_expect", u32_words(
            np.pad(y, ((0, 0), (0, npad - n)), constant_values=0).ravel())),
    ]

    # ---- vector ops ------------------------------------------------------
    # Every op the register map dispatches, with its own tables, so the SoC test
    # covers the config-region sub-decode as well as the arithmetic.
    import math

    lut_lo, lut_hi = build_exp_lut(SM_SCALE_IN)
    sm_x = rng.integers(INT8_MIN, INT8_MAX + 1,
                        size=(args.sm_rows, args.sm_len), dtype=np.int64)
    sm_x[0, :] = 5
    sm_y = qsoftmax(sm_x.astype(np.int16), (lut_lo, lut_hi), SM_SCALE_OUT)
    sm_rq = Requant.from_real_multiplier(1.0 / (float(1 << 15) * SM_SCALE_OUT))

    ln_x = rng.integers(INT8_MIN, INT8_MAX + 1,
                        size=(args.ln_rows, args.ln_len), dtype=np.int64)
    ln_gamma = rng.integers(INT8_MIN, INT8_MAX + 1,
                            size=args.ln_len, dtype=np.int64).astype(np.int8)
    ln_beta = rng.integers(-40, 41, size=args.ln_len, dtype=np.int64).astype(np.int32)
    ln_rq = Requant.from_real_multiplier(
        LN_SCALE_GAMMA * math.sqrt(args.ln_len) / (float(1 << 14) * LN_SCALE_OUT))
    ln_y = qlayernorm(ln_x.astype(np.int8), ln_gamma, ln_beta,
                      LN_SCALE_IN, ln_rq, eps=LN_EPS)
    ln_eps_q = int(round(LN_EPS / (LN_SCALE_IN * LN_SCALE_IN) * args.ln_len**3))

    qa_a = rng.integers(INT8_MIN, INT8_MAX + 1, size=args.vec_n, dtype=np.int64).astype(np.int8)
    qa_b = rng.integers(INT8_MIN, INT8_MAX + 1, size=args.vec_n, dtype=np.int64).astype(np.int8)
    rq_a = Requant.from_real_multiplier(0.75)
    rq_b = Requant.from_real_multiplier(1.25)
    qa_y = qadd(qa_a, qa_b, rq_a, rq_b)

    un_lut = build_unary_lut(gelu, scale_in=8.0 / 127.0, scale_out=4.0 / 127.0)
    un_x = rng.integers(INT8_MIN, INT8_MAX + 1, size=args.vec_n, dtype=np.int64).astype(np.int8)
    un_x[:5] = np.array([INT8_MIN, -1, 0, 1, INT8_MAX], dtype=np.int8)
    un_y = apply_unary_lut(un_x, un_lut)

    def pad16(a: np.ndarray) -> np.ndarray:
        flat = np.asarray(a).ravel()
        pad = (-len(flat)) % 16
        return np.concatenate([flat, np.zeros(pad, dtype=np.int64)])

    out += [
        f"#define VEC_SM_ROWS {args.sm_rows}",
        f"#define VEC_SM_LEN {args.sm_len}",
        f"#define VEC_SM_MULT {int(sm_rq.multiplier)}u",
        f"#define VEC_SM_SHIFT {int(sm_rq.shift)}",
        f"#define VEC_LN_ROWS {args.ln_rows}",
        f"#define VEC_LN_LEN {args.ln_len}",
        f"#define VEC_LN_MULT {int(ln_rq.multiplier)}u",
        f"#define VEC_LN_SHIFT {int(ln_rq.shift)}",
        f"#define VEC_LN_EPS_LO {ln_eps_q & 0xFFFFFFFF}u",
        f"#define VEC_LN_EPS_HI {(ln_eps_q >> 32) & 0xFFFFFFFF}u",
        f"#define VEC_N {args.vec_n}",
        f"#define VEC_QA_MULT_A {int(rq_a.multiplier)}u",
        f"#define VEC_QA_SHIFT_A {int(rq_a.shift)}",
        f"#define VEC_QA_MULT_B {int(rq_b.multiplier)}u",
        f"#define VEC_QA_SHIFT_B {int(rq_b.shift)}",
        "",
        carr("vec_sm_x", u32_words(pad16(sm_x))),
        carr("vec_sm_y", u32_words(pad16(sm_y))),
        carr("vec_ln_x", u32_words(pad16(ln_x))),
        carr("vec_ln_y", u32_words(pad16(ln_y))),
        carr("vec_ln_gamma", [int(v) & 0xFF for v in ln_gamma]),
        carr("vec_ln_beta", [int(v) & 0xFFFFFFFF for v in ln_beta]),
        carr("vec_qa_a", u32_words(pad16(qa_a))),
        carr("vec_qa_b", u32_words(pad16(qa_b))),
        carr("vec_qa_y", u32_words(pad16(qa_y))),
        carr("vec_un_x", u32_words(pad16(un_x))),
        carr("vec_un_y", u32_words(pad16(un_y))),
        carr("vec_un_lut", [int(v) & 0xFF for v in un_lut]),
        carr("vec_exp_lo", [int(v) & 0xFFFF for v in lut_lo]),
        carr("vec_exp_hi", [int(v) & 0xFFFF for v in lut_hi]),
    ]

    args.o.write_text("\n".join(out) + "\n")
    print(f"wrote {args.o} ({m}x{k}x{n}, {kt} k tiles, {nt} n tiles)")


if __name__ == "__main__":
    main()
